const char *root_ca = ""

#ifndef DISABLE_CA_CHECK
#define DISABLE_CA_CHECK 0
#endif

#ifndef CA_DST_X3
#define CA_DST_X3 0
#endif

#ifndef CA_LETS_ENCRYPT
#define CA_LETS_ENCRYPT 0
#endif

#ifndef CA_EMONCMS
#define CA_EMONCMS 1
#endif

#ifndef CA_OPENEVSE
#define CA_OPENEVSE 1
#endif

#ifndef CA_DIGICERT_HIGH_ASSURANCE_EV
#define CA_DIGICERT_HIGH_ASSURANCE_EV 0
#endif

#ifndef CA_OHMHOUR
#define CA_OHMHOUR 1
#endif

#ifndef CA_GITHUB
#define CA_GITHUB 0
#endif

#ifndef CA_AMAZON_1
#define CA_AMAZON_1 1
#endif
  
#ifndef CA_HAUNHAUS
#define CA_HAUNHAUS 0
#endif


#if !DISABLE_CA_CHECK
#if CA_DST_X3 || CA_LETS_ENCRYPT || CA_EMONCMS || CA_OPENEVSE
"-----BEGIN CERTIFICATE-----\r\n"
"MIIDSjCCAjKgAwIBAgIQRK+wgNajJ7qJMDmGLvhAazANBgkqhkiG9w0BAQUFADA/\r\n"
"MSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMT\r\n"
"DkRTVCBSb290IENBIFgzMB4XDTAwMDkzMDIxMTIxOVoXDTIxMDkzMDE0MDExNVow\r\n"
"PzEkMCIGA1UEChMbRGlnaXRhbCBTaWduYXR1cmUgVHJ1c3QgQ28uMRcwFQYDVQQD\r\n"
"Ew5EU1QgUm9vdCBDQSBYMzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB\r\n"
"AN+v6ZdQCINXtMxiZfaQguzH0yxrMMpb7NnDfcdAwRgUi+DoM3ZJKuM/IUmTrE4O\r\n"
"rz5Iy2Xu/NMhD2XSKtkyj4zl93ewEnu1lcCJo6m67XMuegwGMoOifooUMM0RoOEq\r\n"
"OLl5CjH9UL2AZd+3UWODyOKIYepLYYHsUmu5ouJLGiifSKOeDNoJjj4XLh7dIN9b\r\n"
"xiqKqy69cK3FCxolkHRyxXtqqzTWMIn/5WgTe1QLyNau7Fqckh49ZLOMxt+/yUFw\r\n"
"7BZy1SbsOFU5Q9D8/RhcQPGX69Wam40dutolucbY38EVAjqr2m7xPi71XAicPNaD\r\n"
"aeQQmxkqtilX4+U9m5/wAl0CAwEAAaNCMEAwDwYDVR0TAQH/BAUwAwEB/zAOBgNV\r\n"
"HQ8BAf8EBAMCAQYwHQYDVR0OBBYEFMSnsaR7LHH62+FLkHX/xBVghYkQMA0GCSqG\r\n"
"SIb3DQEBBQUAA4IBAQCjGiybFwBcqR7uKGY3Or+Dxz9LwwmglSBd49lZRNI+DT69\r\n"
"ikugdB/OEIKcdBodfpga3csTS7MgROSR6cz8faXbauX+5v3gTt23ADq1cEmv8uXr\r\n"
"AvHRAosZy5Q6XkjEGB5YGV8eAlrwDPGxrancWYaLbumR9YbK+rlmM6pZW87ipxZz\r\n"
"R8srzJmwN0jP41ZL9c8PDHIyh8bwRLtTcm1D9SZImlJnt1ir/md2cXjbDaJWFBM5\r\n"
"JDGFoqgCWjBH4d1QB7wCCZAA62RjYJsWvIjJEubSfZGL+T0yjWW06XyxV3bqxbYo\r\n"
"Ob8VZRzI9neWagqNdwvYkQsEjgfbKbYK7p2CNTUQ\r\n"
"-----END CERTIFICATE-----\r\n"
#endif
#if CA_DIGICERT_HIGH_ASSURANCE_EV || CA_OHMHOUR || CA_GITHUB
"-----BEGIN CERTIFICATE-----\r\n"
"MIIDxTCCAq2gAwIBAgIQAqxcJmoLQJuPC3nyrkYldzANBgkqhkiG9w0BAQUFADBs\r\n"
"MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3\r\n"
"d3cuZGlnaWNlcnQuY29tMSswKQYDVQQDEyJEaWdpQ2VydCBIaWdoIEFzc3VyYW5j\r\n"
"ZSBFViBSb290IENBMB4XDTA2MTExMDAwMDAwMFoXDTMxMTExMDAwMDAwMFowbDEL\r\n"
"MAkGA1UEBhMCVVMxFTATBgNVBAoTDERpZ2lDZXJ0IEluYzEZMBcGA1UECxMQd3d3\r\n"
"LmRpZ2ljZXJ0LmNvbTErMCkGA1UEAxMiRGlnaUNlcnQgSGlnaCBBc3N1cmFuY2Ug\r\n"
"RVYgUm9vdCBDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMbM5XPm\r\n"
"+9S75S0tMqbf5YE/yc0lSbZxKsPVlDRnogocsF9ppkCxxLeyj9CYpKlBWTrT3JTW\r\n"
"PNt0OKRKzE0lgvdKpVMSOO7zSW1xkX5jtqumX8OkhPhPYlG++MXs2ziS4wblCJEM\r\n"
"xChBVfvLWokVfnHoNb9Ncgk9vjo4UFt3MRuNs8ckRZqnrG0AFFoEt7oT61EKmEFB\r\n"
"Ik5lYYeBQVCmeVyJ3hlKV9Uu5l0cUyx+mM0aBhakaHPQNAQTXKFx01p8VdteZOE3\r\n"
"hzBWBOURtCmAEvF5OYiiAhF8J2a3iLd48soKqDirCmTCv2ZdlYTBoSUeh10aUAsg\r\n"
"EsxBu24LUTi4S8sCAwEAAaNjMGEwDgYDVR0PAQH/BAQDAgGGMA8GA1UdEwEB/wQF\r\n"
"MAMBAf8wHQYDVR0OBBYEFLE+w2kD+L9HAdSYJhoIAu9jZCvDMB8GA1UdIwQYMBaA\r\n"
"FLE+w2kD+L9HAdSYJhoIAu9jZCvDMA0GCSqGSIb3DQEBBQUAA4IBAQAcGgaX3Nec\r\n"
"nzyIZgYIVyHbIUf4KmeqvxgydkAQV8GK83rZEWWONfqe/EW1ntlMMUu4kehDLI6z\r\n"
"eM7b41N5cdblIZQB2lWHmiRk9opmzN6cN82oNLFpmyPInngiK3BD41VHMWEZ71jF\r\n"
"hS9OMPagMRYjyOfiZRYzy78aG6A9+MpeizGLYAiJLQwGXFK3xPkKmNEVX58Svnw2\r\n"
"Yzi9RKR/5CYrCsSXaQ3pjOLAEFe4yHYSkVXySGnYvCoCWw9E1CAx2/S6cCZdkGCe\r\n"
"vEsXCS+0yx5DaMkHJ8HSXPfqIbloEpw8nL+e/IBcm2PN7EeqJSdnoDfzAIJ9VNep\r\n"
"+OkuE6N36B9K\r\n"
"-----END CERTIFICATE-----\r\n"
#endif
#if CA_AMAZON_1
"-----BEGIN CERTIFICATE-----\r\n"
"MIIDQTCCAimgAwIBAgITBmyfz5m/jAo54vB4ikPmljZbyjANBgkqhkiG9w0BAQsF\r\n"
"ADA5MQswCQYDVQQGEwJVUzEPMA0GA1UEChMGQW1hem9uMRkwFwYDVQQDExBBbWF6\r\n"
"b24gUm9vdCBDQSAxMB4XDTE1MDUyNjAwMDAwMFoXDTM4MDExNzAwMDAwMFowOTEL\r\n"
"MAkGA1UEBhMCVVMxDzANBgNVBAoTBkFtYXpvbjEZMBcGA1UEAxMQQW1hem9uIFJv\r\n"
"b3QgQ0EgMTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALJ4gHHKeNXj\r\n"
"ca9HgFB0fW7Y14h29Jlo91ghYPl0hAEvrAIthtOgQ3pOsqTQNroBvo3bSMgHFzZM\r\n"
"9O6II8c+6zf1tRn4SWiw3te5djgdYZ6k/oI2peVKVuRF4fn9tBb6dNqcmzU5L/qw\r\n"
"IFAGbHrQgLKm+a/sRxmPUDgH3KKHOVj4utWp+UhnMJbulHheb4mjUcAwhmahRWa6\r\n"
"VOujw5H5SNz/0egwLX0tdHA114gk957EWW67c4cX8jJGKLhD+rcdqsq08p8kDi1L\r\n"
"93FcXmn/6pUCyziKrlA4b9v7LWIbxcceVOF34GfID5yHI9Y/QCB/IIDEgEw+OyQm\r\n"
"jgSubJrIqg0CAwEAAaNCMEAwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMC\r\n"
"AYYwHQYDVR0OBBYEFIQYzIU07LwMlJQuCFmcx7IQTgoIMA0GCSqGSIb3DQEBCwUA\r\n"
"A4IBAQCY8jdaQZChGsV2USggNiMOruYou6r4lK5IpDB/G/wkjUu0yKGX9rbxenDI\r\n"
"U5PMCCjjmCXPI6T53iHTfIUJrU6adTrCC2qJeHZERxhlbI1Bjjt/msv0tadQ1wUs\r\n"
"N+gDS63pYaACbvXy8MWy7Vu33PqUXHeeE6V/Uq2V8viTO96LXFvKWlJbYK8U90vv\r\n"
"o/ufQJVtMVT8QtPHRh8jrdkPSHCa2XV4cdFyQzR1bldZwgJcJmApzyMZFo6IQ6XU\r\n"
"5MsI+yMRQ+hDKXJioaldXgjUkK642M4UwtBV8ob2xJNDd2ZhwLnoQdeXeGADbkpy\r\n"
"rqXRfboQnoZsG4q5WTP468SQvvG5\r\n"
"-----END CERTIFICATE-----\r\n"
#if CA_HAUN_HAUS
"-----BEGIN CERTIFICATE-----\r\n"
"MIIEJjCCAw6gAwIBAgIUY9rP21/YEwjq0w98viH3eRr4yyUwDQYJKoZIhvcNAQEL\r\n"
"BQAwMDESMBAGA1UECgwJSGF1bi5IYXVzMRowGAYDVQQDDBFIYXVuLkhhdXMgUm9v\r\n"
"dCBDQTAgFw0yMDEyMTEwMTM2NDVaGA8yMDUxMDUyNzAxMzY0NVowMDESMBAGA1UE\r\n"
"CgwJSGF1bi5IYXVzMRowGAYDVQQDDBFIYXVuLkhhdXMgUm9vdCBDQTCCASIwDQYJ\r\n"
"KoZIhvcNAQEBBQADggEPADCCAQoCggEBAKT4CyOCcMZ1C+RKMb3rzMjmsMcLpiTJ\r\n"
"OvFUKtn0Tl54bzlEmsvMKRqUbp0ISOGt1WYLQnoSL7K28C4fW+7VExUOwAvTGPxp\r\n"
"1wH6AC7hitEJGKvG4rDv9yWEtSv1BN+/eMgJ6bjqGNSUZdLLCW3/GSB6febWWlj5\r\n"
"ZSmsD1MKnDIkQzNF1rpQc/ClHo6r3Q+kDecbfH81IlMnhBn78tsfVd/AHpdUZ+6C\r\n"
"u570GPCFyndkgZQpQnqHpYBJkNiWgurln+ziqmstpVHsrfD2OU/XGfG7dHck4XUZ\r\n"
"XiuEKV4X9U6KfK0II0LeMGAift0YsuZZBswMrgk5rUXPYwqjnORmUW0CAwEAAaOC\r\n"
"ATQwggEwMAwGA1UdEwQFMAMBAf8wJQYJYIZIAYb4QgENBBgWFkhhdW4uSGF1cyBQ\r\n"
"cml2YXRlIFJvb3QwCwYDVR0PBAQDAgEGMDcGCCsGAQUFBwEBBCswKTAnBggrBgEF\r\n"
"BQcwAYYbaHR0cDovL29jc3Atcm9vdC5oYXVuLmhhdXMvMDMGA1UdHwQsMCowKKAm\r\n"
"oCSGImh0dHA6Ly9jcmwtcm9vdC5oYXVuLmhhdXMvcm9vdC5jcmwwfgYDVR0eBHcw\r\n"
"daBzMAuCCWhhdW4uaGF1czAMggouaGF1bi5oYXVzMAqHCMCoKgD///8AMAqHCMCo\r\n"
"jgD///8AMAqHCMCoGwD///8AMAqHCMCowAD//8AAMBikFjAUMRIwEAYDVQQKDAlI\r\n"
"YXVuLkhhdXMwDIEKQGhhdW4uaGF1czANBgkqhkiG9w0BAQsFAAOCAQEApFWnQ9Se\r\n"
"lUlIOjQ+7t+axir2IZpMYqrRx6fh9fxt65WxxT8KiW4xEDJz1qIXF9SNLOuAV/Ja\r\n"
"07ZcM7ALZ3jEYfYQEIOUnqppmT3wprM1DvvReHnjvtlH4viCDhJh3xjjxuoxEj+3\r\n"
"fq3vEziaZTQcDRUQ8VasxPS3SnJ9PGRiOxVUVXwIwWkHsOGvPtbj6gW01N140Ttu\r\n"
"K7Itdy84h00JE5W1W9u27CLYOVthBbfl7LKtTlO2zDlPT20A2T/3liA7f1dRWZej\r\n"
"RiksysuU2xZgIFLksul1ZJxx0ujVXrW00K0vbGt0SOHZtNUGlZe6tk47uN9WEvhW\r\n"
"Kvd0VhjOfEc2IA==\r\n"
"-----END CERTIFICATE-----\r\n"
#endif
#endif
#else
"*"
#endif
;
